### PR TITLE
Don't include sys/random.h

### LINKED ISSUE #101: splitmix-0.1.3.1 cannot be built on OpenBSD
See https://cirrus-ci.com/task/5972040047394816 and/or https://github.com/haskell/text/pull/643/checks?check_run_id=44950107780:
```
Failed to build splitmix-0.1.3.1.
Build log (
/tmp/.cabal/logs/ghc-9.8.3/splitmix-0.1.3.1-eee97be94a007d3a1d64b41d0a0ebc39de6917f24f2de65c1109d383306f099a.log
):
Configuring library for splitmix-0.1.3.1...
Preprocessing library for splitmix-0.1.3.1...
Building library for splitmix-0.1.3.1...
[1 of 4] Compiling Data.Bits.Compat ( src-compat/Data/Bits/Compat.hs, dist/build/Data/Bits/Compat.o, dist/build/Data/Bits/Compat.dyn_o )
[2 of 4] Compiling System.Random.SplitMix.Init ( src/System/Random/SplitMix/Init.hs, dist/build/System/Random/SplitMix/Init.o, dist/build/System/Random/SplitMix/Init.dyn_o )
[3 of 4] Compiling System.Random.SplitMix ( src/System/Random/SplitMix.hs, dist/build/System/Random/SplitMix.o, dist/build/System/Random/SplitMix.dyn_o )
[4 of 4] Compiling System.Random.SplitMix32 ( src/System/Random/SplitMix32.hs, dist/build/System/Random/SplitMix32.o, dist/build/System/Random/SplitMix32.dyn_o )
cbits-unix/init.c:3:10: error:
     fatal error: 'sys/random.h' file not found
  |
3 | #include <sys/random.h>
  |          ^
#include <sys/random.h>
         ^~~~~~~~~~~~~~
1 error generated.
`clang' failed in phase `C Compiler'. (Exit code: 1)
Error: [Cabal-7125]
Failed to build splitmix-0.1.3.1 (which is required by test:tests from text-2.1.2). See the build log above for details.
```

Might be very well me misconfiguring OpenBSD, although it used to work with `splitmix-0.1.1`.

### PR DESCRIPTION
**Pull request by phadej**
As far as I can trace, Android doesn't need it:
https://android.googlesource.com/platform/bionic/+/7110157e941f0895638c81872b535d8781cf79cf

OpenBSD doesnt have that header. So lets not include it.

Resolves #101

### CODE REVIEW

**Comment by PeterHajdu** [comment]
Can I help somehow to advance this pull request?

**Comment by phadej** [comment]
@PeterHajdu write a documentation on how to setup OpenBSD Haskell test jobs (on GHA).

This, #106 and #107 don't fix nor break anything as far as automated testing is concerned.

**Comment by blackgnezdo** [comment]
Superficially, there's https://github.com/vmactions/openbsd-vm. One should be able to `pkg_add ghc cabal` and go from tehre.

**Comment by phadej** [comment]
Merged as part of https://github.com/haskellari/splitmix/pull/109
