### ISSUE TITLE
splitmix-0.1.3.1 cannot be built on OpenBSD

### ISSUE THREAD

**Issue by Bodigrim** [haskellari/splitmix#101]
See https://cirrus-ci.com/task/5972040047394816 and/or https://github.com/haskell/text/pull/643/checks?check_run_id=44950107780:
```
Failed to build splitmix-0.1.3.1.
Build log (
/tmp/.cabal/logs/ghc-9.8.3/splitmix-0.1.3.1-eee97be94a007d3a1d64b41d0a0ebc39de6917f24f2de65c1109d383306f099a.log
):
Configuring library for splitmix-0.1.3.1...
Preprocessing library for splitmix-0.1.3.1...
Building library for splitmix-0.1.3.1...
[1 of 4] Compiling Data.Bits.Compat ( src-compat/Data/Bits/Compat.hs, dist/build/Data/Bits/Compat.o, dist/build/Data/Bits/Compat.dyn_o )
[2 of 4] Compiling System.Random.SplitMix.Init ( src/System/Random/SplitMix/Init.hs, dist/build/System/Random/SplitMix/Init.o, dist/build/System/Random/SplitMix/Init.dyn_o )
[3 of 4] Compiling System.Random.SplitMix ( src/System/Random/SplitMix.hs, dist/build/System/Random/SplitMix.o, dist/build/System/Random/SplitMix.dyn_o )
[4 of 4] Compiling System.Random.SplitMix32 ( src/System/Random/SplitMix32.hs, dist/build/System/Random/SplitMix32.o, dist/build/System/Random/SplitMix32.dyn_o )
cbits-unix/init.c:3:10: error:
     fatal error: 'sys/random.h' file not found
  |
3 | #include <sys/random.h>
  |          ^
#include <sys/random.h>
         ^~~~~~~~~~~~~~
1 error generated.
`clang' failed in phase `C Compiler'. (Exit code: 1)
Error: [Cabal-7125]
Failed to build splitmix-0.1.3.1 (which is required by test:tests from text-2.1.2). See the build log above for details.
```

Might be very well me misconfiguring OpenBSD, although it used to work with `splitmix-0.1.1`.

**Comment by phadej** [comment]
sys/random.h was included because it's required by Android (bionic), see https://github.com/haskellari/splitmix/pull/97

POSIX says that `getentropy` should be visible through in `unistd.h`, but neither Google nor Apple didn't expose it there.
"technically" I could remove the `sys/random.h` include as it's not needed by anything I test atm, and Google's bionic does something own and I have no sympathy for Google breaking what works on Linux otherwise. @hamishmack 

Another solution I can see is to make `splitmix` a `build-type: Configure` package which might make some people's life harder too, but I have no resources to test on every platforms and maintain hand-crafted CPP conditionals (especially on non-GHC-tier-1 ones  https://gitlab.haskell.org/ghc/ghc/-/wikis/platforms).

**Comment by phadej** [comment]
I guess another option is to use `getentropy` initialization only on Linux (i.e. platform I explicitly test on), and let other unixes be initialized using `time`. But this will break WASM, as that's another platform which I don't test explicitly on. I kind of know that `getentropy` works there, but I don't know for sure which headers are required there.

**Comment by phadej** [comment]
So far, I'm bending towards dropping the `sys/random.h` include. I have no idea how to test Andoid bionic. AFAICT, it's not a platform support by GHC at all.

**Comment by phadej** [comment]
@Bodigrim according to gnulib docs https://www.gnu.org/software/gnulib/manual/html_node/sys_002frandom_002eh.html, `sys/random.h` doesn't exist in OpenBSD 7.5 (maybe it's added since, as it also says it didn't exist in NetBSD 9.3, but you say that it does indeed exist).

**Comment by Bodigrim** [comment]
(Something interesting is going on with [the NetBSD build](https://cirrus-ci.com/task/6246394740080640): it started building directly from `QuickCheck`. This suggests that system package maintainers configured GHC installation in such way that `splitmix` / `random` reside in the global package DB and are not to be rebuilt?..)

----

It seems that NetBSD gained `getrandom(2)` in 10.0: https://man.netbsd.org/NetBSD-9.4/getrandom.2 does not yet exist, but https://man.netbsd.org/NetBSD-10.0/getrandom.2 does. Even DragonFlyBSD has it: https://leaf.dragonflybsd.org/cgi/web-man?command=getrandom&section=2. So let's hope that OpenBSD follows the suit soon.

**Comment by phadej** [comment]
... or Android fixes its headers, as OpenBSD has `getentropy`. The `#include <sys/random.h>` is there just for Android. *I don't like that*.

Speaking of what, looking at https://android.googlesource.com/platform/bionic/+/master/libc/include/unistd.h there is 

```
David Benjamin	7110157	2023-07-15 19:24:32 -0400	[diff] [blame]	38	#include <bits/getentropy.h>
```

So it seems that `getentropy` should be available through `unistd.h`. @hamishmack why did you add `sys/random.h` include in #97. Now I'm leaning towards removing that include. it's wrong, and TBH if I had to choose I'd prefer OpenBSD over Android support.

**Comment by phadej** [comment]
I'm afraid centos7 just wont work. It's using too old glibc. Also "CentOS 7 reached its end of life (EOL) on June 30, 2024"

**Comment by blackgnezdo** [comment]
> I'm afraid centos7 just wont work. It's using too old glibc. Also "CentOS 7 reached its end of life (EOL) on June 30, 2024". Similarly debian 9 is ancient distribution.
> 
> They just don't have `getentropy` at all. It's not the same issue as with OpenBSD.

Given that `sys/random.h` is not a standard include I naturally prefer that the compliant system I use (OpenBSD) is fixed. If workaround have to be put in, the non-standard systems should be singled out in those.

**Comment by blackgnezdo** [comment]
> > I'm afraid centos7 just wont work. It's using too old glibc. Also "CentOS 7 reached its end of life (EOL) on June 30, 2024". Similarly debian 9 is ancient distribution.
> > They just don't have `getentropy` at all. It's not the same issue as with OpenBSD.
> 
> Given that `sys/random.h` is not a standard include I naturally prefer that the compliant system I use (OpenBSD) works. If workaround have to be put in, the non-standard systems should be singled out in those.

**Comment by PeterHajdu** [comment]
I've just opened a pull request that should fix this issue.  I've tested it on Linux and OpenBSD7.7.
